[project]
requires-python = ">=3.6"

# Aside - in pyproject.toml you should always specify minimal build
# system options, like this:

[build-system]
requires = ["setuptools>=42", "wheel","numpy>=1.19.1"]
build-backend = "setuptools.build_meta"